# Generated by Django 5.1.6 on 2025-02-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата уроку')),
                ('class_group', models.CharField(max_length=10, verbose_name='Клас')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема уроку')),
                ('goal', models.TextField(verbose_name='Мета уроку')),
                ('lesson_type', models.CharField(max_length=50, verbose_name='Тип уроку')),
                ('materials', models.TextField(blank=True, verbose_name='Матеріали')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнє завдання')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
        ),
    ]
