# Generated by Django 5.1.6 on 2025-02-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarplan',
            name='subject',
            field=models.CharField(default='Математика', max_length=50, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='calendarplan',
            name='class_group',
            field=models.CharField(choices=[('5-Математика', '5-й клас (Математика)'), ('7-Алгебра', '7-й клас (Алгебра)'), ('7-Геометрія', '7-й клас (Геометрія)'), ('8-Алгебра', '8-й клас (Алгебра)'), ('8-Геометрія', '8-й клас (Геометрія)'), ('9-Алгебра', '9-й клас (Алгебра)'), ('9-Геометрія', '9-й клас (Геометрія)')], max_length=50, verbose_name='Клас'),
        ),
    ]
